window.MA_DASHBOARD_DATA = {
  meta: {
    cycle: "2026-2027",
    scope: "Metas + Rhino normalizado",
    updatedAt: "Cargado desde Concentrado (2).xlsx"
  },
  kpis: [
    { key: "meta_total", label: "Meta total", value: 3537, format: "number", helper: "EXANI I + EXANI II" },
    { key: "inscritos_reales", label: "Inscritos reales", value: 122, format: "number", helper: "Conteo válido en Rhino" },
    { key: "gap_vs_meta_total", label: "Gap", value: -3415, format: "number", helper: "Real - meta" },
    { key: "cumplimiento_pct", label: "% cumplimiento", value: 0.03449250777, format: "percent", helper: "Contra meta total" },
    { key: "campus_activos", label: "Campus activos", value: 4, format: "number", helper: "Con inscritos válidos" },
    { key: "meses_inicio_activos", label: "Inicios activos", value: 2, format: "number", helper: "Con inscritos válidos" }
  ],
  campus: [
    { campus: "Campeche", temario: "EXANI II", goal: 150, real: 0, gap: -150, compliance: 0, semaphore: "rojo" },
    { campus: "Caucel / CEDU Noel / Humanitas", temario: "EXANI II", goal: 240, real: 0, gap: -240, compliance: 0, semaphore: "rojo" },
    { campus: "Centro", temario: "EXANI II", goal: 1215, real: 100, gap: -1115, compliance: 0.0823045267489712, semaphore: "rojo" },
    { campus: "Intensivo Presencial", temario: "EXANI II", goal: 120, real: 0, gap: -120, compliance: 0, semaphore: "rojo" },
    { campus: "Intensivo Virtual", temario: "EXANI II", goal: 120, real: 0, gap: -120, compliance: 0, semaphore: "rojo" },
    { campus: "LAB", temario: "EXANI II", goal: 160, real: 0, gap: -160, compliance: 0, semaphore: "rojo" },
    { campus: "Norte / Patria", temario: "EXANI II", goal: 180, real: 0, gap: -180, compliance: 0, semaphore: "rojo" },
    { campus: "Playa del Carmen", temario: "EXANI II", goal: 190, real: 4, gap: -186, compliance: 0.02105263157894737, semaphore: "rojo" },
    { campus: "Veracruz", temario: "EXANI II", goal: 278, real: 0, gap: -278, compliance: 0, semaphore: "rojo" },
    { campus: "Virtual", temario: "EXANI II", goal: 1200, real: 17, gap: -1183, compliance: 0.01416666666666667, semaphore: "rojo" },
    { campus: "Campeche", temario: "EXANI I", goal: 44, real: 0, gap: -44, compliance: 0, semaphore: "rojo" },
    { campus: "Centro", temario: "EXANI I", goal: 180, real: 0, gap: -180, compliance: 0, semaphore: "rojo" },
    { campus: "LAB", temario: "EXANI I", goal: 100, real: 0, gap: -100, compliance: 0, semaphore: "rojo" },
    { campus: "Norte / Patria", temario: "EXANI I", goal: 100, real: 0, gap: -100, compliance: 0, semaphore: "rojo" },
    { campus: "Virtual", temario: "EXANI I", goal: 100, real: 1, gap: -99, compliance: 0.01, semaphore: "rojo" }
  ],
  starts: [
    { startMonth: "2026-09", campus: "Campeche", temario: "EXANI II", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Campeche", temario: "EXANI II", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-02", campus: "Campeche", temario: "EXANI II", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-09", campus: "Caucel / CEDU Noel / Humanitas", temario: "EXANI II", goal: 120, real: 0, gap: -120, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-11", campus: "Caucel / CEDU Noel / Humanitas", temario: "EXANI II", goal: 60, real: 0, gap: -60, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "Caucel / CEDU Noel / Humanitas", temario: "EXANI II", goal: 60, real: 0, gap: -60, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-09", campus: "Centro", temario: "EXANI II", goal: 549, real: 96, gap: -453, compliance: 0.17486338797814208, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Centro", temario: "EXANI II", goal: 282, real: 0, gap: -282, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-11", campus: "Centro", temario: "EXANI II", goal: 194, real: 0, gap: -194, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-12", campus: "Centro", temario: "EXANI II", goal: 190, real: 0, gap: -190, compliance: 0, semaphore: "rojo" },
    { startMonth: "Intensivo Presencial", campus: "Centro", temario: "EXANI II", goal: 0, real: 4, gap: 4, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "Intensivo Presencial", temario: "EXANI II", goal: 120, real: 0, gap: -120, compliance: 0, semaphore: "rojo" },
    { startMonth: "Intensivo Virtual", campus: "Intensivo Virtual", temario: "EXANI II", goal: 0, real: 0, gap: 0, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "Intensivo Virtual", temario: "EXANI II", goal: 120, real: 0, gap: -120, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-09", campus: "LAB", temario: "EXANI II", goal: 80, real: 0, gap: -80, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "LAB", temario: "EXANI II", goal: 80, real: 0, gap: -80, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Norte / Patria", temario: "EXANI II", goal: 90, real: 0, gap: -90, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "Norte / Patria", temario: "EXANI II", goal: 90, real: 0, gap: -90, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-09", campus: "Playa del Carmen", temario: "EXANI II", goal: 100, real: 4, gap: -96, compliance: 0.04, semaphore: "rojo" },
    { startMonth: "2027-02", campus: "Playa del Carmen", temario: "EXANI II", goal: 90, real: 0, gap: -90, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-11", campus: "Veracruz", temario: "EXANI II", goal: 100, real: 0, gap: -100, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-03", campus: "Veracruz", temario: "EXANI II", goal: 178, real: 0, gap: -178, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-09", campus: "Virtual", temario: "EXANI II", goal: 340, real: 17, gap: -323, compliance: 0.05, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Virtual", temario: "EXANI II", goal: 340, real: 0, gap: -340, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-11", campus: "Virtual", temario: "EXANI II", goal: 240, real: 0, gap: -240, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "Virtual", temario: "EXANI II", goal: 280, real: 0, gap: -280, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Campeche", temario: "EXANI I", goal: 22, real: 0, gap: -22, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-02", campus: "Campeche", temario: "EXANI I", goal: 22, real: 0, gap: -22, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Centro", temario: "EXANI I", goal: 60, real: 0, gap: -60, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-11", campus: "Centro", temario: "EXANI I", goal: 60, real: 0, gap: -60, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-01", campus: "Centro", temario: "EXANI I", goal: 60, real: 0, gap: -60, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "LAB", temario: "EXANI I", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2027-02", campus: "LAB", temario: "EXANI I", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Norte / Patria", temario: "EXANI I", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-11", campus: "Norte / Patria", temario: "EXANI I", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" },
    { startMonth: "2026-10", campus: "Virtual", temario: "EXANI I", goal: 50, real: 1, gap: -49, compliance: 0.02, semaphore: "rojo" },
    { startMonth: "2027-02", campus: "Virtual", temario: "EXANI I", goal: 50, real: 0, gap: -50, compliance: 0, semaphore: "rojo" }
  ]
};
